swiftmailer:
    #url: '%env(MAILER_URL)%'
    #spool: { type: 'memory' }
    transport: smtp
    host: maildev
    port: 25
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'