version: '2'

services:

    mysql:
        container_name: container_mysql
        image: mysql:5.7
        volumes:
            - /var/lib/boot2docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    php:
        container_name: container_phpfpm
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - /var/www/photographer_symfony:/var/www/symfony
        links:
            - maildev:maildev

    nginx:
        container_name: container_nginx
        build:
            context: docker/nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
                SERVER_NAME: ${SERVER_NAME}
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    phpmyadmin:
        container_name: container_admin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        links:
            - mysql

    maildev:
        container_name: container_maildev
        image: djfarrelly/maildev
        ports:
            - "1080:80"








