index:
    path: /
    controller: App\Controller\DefaultController::index

gallery_index:
    path: /gallery
    controller: App\Controller\GalleryController::index

thumbnails:
    path: /thumbnails/{id}
    controller: App\Controller\GalleryController::thumbnailsList

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"