index:
    path: /
    controller: App\Controller\DefaultController::index

# *** gallery routes ***
gallery_index:
    path: /gallery
    controller: App\Controller\GalleryController::index

thumbnails:
    path: /thumbnails/{id}
    controller: App\Controller\GalleryController::thumbnailsList

like_image:
    path: /like
    controller: App\Controller\GalleryController::likeImage

user_account:
    path: /account
    controller: App\Controller\UserController::index

# *** blog routes ***
blog_index:
    path: /blog
    controller: App\Controller\BlogController::index

show_post:
    path: /blog/{id}
    controller: App\Controller\BlogController::showPost

# *** contact form routes ***
contact:
    path: /contact
    controller: App\Controller\ContactController::index

# *** About route controller *** #

about:
    path: /about
    controller: App\Controller\AboutController::index

# *** security routes ****
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"